- name: 创建 etcd 的证书请求配置
  template: 
    src: etcd-openssl.cnf.j2
    dest: /etc/kubernetes/pki/etcd/etcd-openssl.cnf
    owner: root
    mode: 0644

- name: 创建 etcd-ca 根证书私钥
  shell: openssl genrsa -out /etc/kubernetes/pki/etcd/ca.key 2048
  when: etcd_ca_key_stat.stat.isreg is not defined

- name: 创建 etcd-ca 根证书
  shell: >
    openssl req -x509 -new -nodes -extensions v3_ca
    -subj "/CN=kubernetes"
    -config /etc/kubernetes/pki/etcd/etcd-openssl.cnf
    -key /etc/kubernetes/pki/etcd/ca.key
    -out /etc/kubernetes/pki/etcd/ca.crt
    -days {{ etcd_ca_certs_expired }}
  when: etcd_ca_crt_stat.stat.isreg is not defined

- name: 创建 etcd-server 证书私钥
  shell: openssl genrsa -out /etc/kubernetes/pki/etcd/server.key 2048
  when: etcd_server_key_stat.stat.isreg is not defined

- name: 检查 etcd-server 证书状态
  stat:
    path: /etc/kubernetes/pki/etcd/server.crt
  register: etcd_server_crt_stat

- name: 验证 CA 证书和私钥匹配性
  shell: |
    if [ -f /etc/kubernetes/pki/etcd/ca.crt ] && [ -f /etc/kubernetes/pki/etcd/ca.key ]; then
      cert_modulus=$(openssl x509 -noout -modulus -in /etc/kubernetes/pki/etcd/ca.crt 2>/dev/null | openssl md5 2>/dev/null)
      key_modulus=$(openssl rsa -noout -modulus -in /etc/kubernetes/pki/etcd/ca.key 2>/dev/null | openssl md5 2>/dev/null)
      if [ "$cert_modulus" != "$key_modulus" ] || [ -z "$cert_modulus" ] || [ -z "$key_modulus" ]; then
        echo "CA certificate and key do not match, need cleanup"
        exit 1
      else
        echo "CA certificate and key match"
        exit 0
      fi
    else
      echo "CA certificate or key missing"
      exit 0
    fi
  ignore_errors: yes
  register: ca_validation_result

- name: 清理损坏的证书文件
  shell: |
    echo "Cleaning up mismatched certificates..."
    rm -f /etc/kubernetes/pki/etcd/{server,peer,healthcheck-client}.{crt,csr}
    rm -f /etc/kubernetes/pki/apiserver-etcd-client.{crt,csr}
    rm -f /etc/kubernetes/pki/etcd/ca.{crt,srl}
    echo "Certificate cleanup completed"
  when: ca_validation_result.rc == 1
  register: cert_cleanup_result

- name: 重新检查 CA 证书状态（清理后）
  stat:
    path: /etc/kubernetes/pki/etcd/ca.crt
  register: etcd_ca_crt_stat_after_cleanup

- name: 重新生成 CA 证书（如果被清理了）
  shell: >
    openssl req -x509 -new -nodes -extensions v3_ca
    -subj "/CN=kubernetes"
    -config /etc/kubernetes/pki/etcd/etcd-openssl.cnf
    -key /etc/kubernetes/pki/etcd/ca.key
    -out /etc/kubernetes/pki/etcd/ca.crt
    -days {{ etcd_ca_certs_expired }}
  when: not etcd_ca_crt_stat_after_cleanup.stat.exists

- name: 创建 etcd-server 证书请求
  shell: >
    openssl req -new 
    -key /etc/kubernetes/pki/etcd/server.key 
    -subj "/CN=master" 
    -out /etc/kubernetes/pki/etcd/server.csr
  when: not etcd_server_crt_stat.stat.exists or (cert_cleanup_result is defined and cert_cleanup_result.changed)

- name: 创建 etcd-server 证书
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_peer 
    -extfile /etc/kubernetes/pki/etcd/etcd-openssl.cnf 
    -CA /etc/kubernetes/pki/etcd/ca.crt 
    -CAkey /etc/kubernetes/pki/etcd/ca.key 
    -in /etc/kubernetes/pki/etcd/server.csr 
    -out /etc/kubernetes/pki/etcd/server.crt
    -days {{ etcd_certs_expired }}
  when: not etcd_server_crt_stat.stat.exists or (cert_cleanup_result is defined and cert_cleanup_result.changed) 

- name: 创建 etcd-peer 证书私钥
  shell: openssl genrsa -out /etc/kubernetes/pki/etcd/peer.key 2048
  when: etcd_peer_key_stat.stat.isreg is not defined

- name: 检查 etcd-peer 证书状态
  stat:
    path: /etc/kubernetes/pki/etcd/peer.crt
  register: etcd_peer_crt_stat

- name: 创建 etcd-peer 证书请求
  shell: >
    openssl req -new 
    -key /etc/kubernetes/pki/etcd/peer.key 
    -subj "/CN=master" 
    -out /etc/kubernetes/pki/etcd/peer.csr
  when: not etcd_peer_crt_stat.stat.exists or (cert_cleanup_result is defined and cert_cleanup_result.changed)

- name: 创建 etcd-peer 证书
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_peer 
    -extfile /etc/kubernetes/pki/etcd/etcd-openssl.cnf 
    -CA /etc/kubernetes/pki/etcd/ca.crt 
    -CAkey /etc/kubernetes/pki/etcd/ca.key 
    -in /etc/kubernetes/pki/etcd/peer.csr 
    -out /etc/kubernetes/pki/etcd/peer.crt
    -days {{ etcd_certs_expired }}
  when: not etcd_peer_crt_stat.stat.exists or (cert_cleanup_result is defined and cert_cleanup_result.changed) 

- name: 创建 apiserver-etcd-client 证书私钥
  shell: openssl genrsa -out /etc/kubernetes/pki/apiserver-etcd-client.key 2048
  when: apiserver_etcd_client_key_stat.stat.isreg is not defined

- name: 检查 apiserver-etcd-client 证书状态
  stat:
    path: /etc/kubernetes/pki/apiserver-etcd-client.crt
  register: apiserver_etcd_client_crt_stat

- name: 创建 apiserver-etcd-client 证书请求
  shell: >
    openssl req -new 
    -key /etc/kubernetes/pki/apiserver-etcd-client.key
    -subj "/CN=kube-apiserver-etcd-client/O=system:masters" 
    -out /etc/kubernetes/pki/apiserver-etcd-client.csr
  when: not apiserver_etcd_client_crt_stat.stat.exists or (cert_cleanup_result is defined and cert_cleanup_result.changed)

- name: 创建 apiserver-etcd-client 证书
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_client 
    -extfile /etc/kubernetes/pki/etcd/etcd-openssl.cnf 
    -CA /etc/kubernetes/pki/etcd/ca.crt 
    -CAkey /etc/kubernetes/pki/etcd/ca.key 
    -in /etc/kubernetes/pki/apiserver-etcd-client.csr
    -out /etc/kubernetes/pki/apiserver-etcd-client.crt
    -days {{ etcd_certs_expired }}
  when: not apiserver_etcd_client_crt_stat.stat.exists or (cert_cleanup_result is defined and cert_cleanup_result.changed) 

- name: 创建 etcd-healthcheck-client 证书私钥
  shell: openssl genrsa -out /etc/kubernetes/pki/etcd/healthcheck-client.key 2048
  when: etcd_healthcheck_client_key_stat.stat.isreg is not defined

- name: 检查 etcd-healthcheck-client 证书状态
  stat:
    path: /etc/kubernetes/pki/etcd/healthcheck-client.crt
  register: etcd_healthcheck_client_crt_stat

- name: 创建 etcd-healthcheck-client 证书请求
  shell: >
    openssl req -new -key /etc/kubernetes/pki/etcd/healthcheck-client.key 
    -subj "/CN=kube-etcd-healthcheck-client/O=system:masters" 
    -out /etc/kubernetes/pki/etcd/healthcheck-client.csr
  when: not etcd_healthcheck_client_crt_stat.stat.exists or (cert_cleanup_result is defined and cert_cleanup_result.changed)

- name: 创建 etcd-healthcheck-client 证书
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_client 
    -extfile /etc/kubernetes/pki/etcd/etcd-openssl.cnf 
    -CA /etc/kubernetes/pki/etcd/ca.crt 
    -CAkey /etc/kubernetes/pki/etcd/ca.key 
    -in /etc/kubernetes/pki/etcd/healthcheck-client.csr 
    -out /etc/kubernetes/pki/etcd/healthcheck-client.crt
    -days {{ etcd_certs_expired }}
  when: not etcd_healthcheck_client_crt_stat.stat.exists or (cert_cleanup_result is defined and cert_cleanup_result.changed) 

- name: 检索需要清理的 etcd 证书请求文件
  find:
    paths: /etc/kubernetes/pki/etcd
    patterns: '*.csr'
  register: files_to_purge_for_csr

- name: 清理 etcd 节点证书请求文件
  file:
    path: "{{ item.path }}"
    state: absent
  no_log: true
  with_items: "{{ files_to_purge_for_csr.files }}"
